# Generated by Django 5.1.6 on 2025-03-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='地址'),
        ),
    ]
